In [33]:
#Upload Your Dataset
from google.colab import files

uploaded = files.upload()

Saving marketing.csv to marketing.csv

In [45]:
#Load the Dataset and View Basic Info
import pandas as pd

df = pd.read_csv("marketing.csv", sep='\t')
print("Initial shape:", df.shape)
df.head()

Initial shape: (2240, 29)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0

In [49]:
#check missing values
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [52]:
#handling missing values
df['Income'].fillna(df['Income'].mean(), inplace=True)

0
0

In [53]:
#Remove Duplicate Rows
df = df.drop_duplicates()

In [54]:
#Standardize Text Columns
df['Education'] = df['Education'].str.strip().str.lower()
df['Marital_Status'] = df['Marital_Status'].str.strip().str.lower()

In [ ]:
#Convert Date Column to Proper Format
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])
df['Dt_Customer'] = df['Dt_Customer'].dt.strftime('%Y-%m-%d')

In [55]:
#Clean Column Names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [56]:
#Ensure Data Types Are Correct
df['income'] = df['income'].astype(float)

cleaned shape: (2240, 29)

In [ ]:
# Save cleaned data to a new CSV
df.to_csv("cleaned_customer_personality.csv", index=False)
print("Cleaned dataset saved as cleaned_customer_personality.csv")

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2240 non-null   int64
 1   year_birth           2240 non-null   int64
 2   education            2240 non-null   object
 3   marital_status       2240 non-null   object
 4   income               2240 non-null   float64
 5   kidhome              2240 non-null   int64
 6   teenhome             2240 non-null   int64
 7   dt_customer          2240 non-null   object
 8   recency              2240 non-null   int64
 9   mntwines             2240 non-null   int64
 10  mntfruits            2240 non-null   int64
 11  mntmeatproducts      2240 non-null   int64
 12  mntfishproducts      2240 non-null   int64
 13  mntsweetproducts     2240 non-null   int64
 14  mntgoldprods         2240 non-null   int64
 15  numdealspurchases    2240 non-null   int64
 16  numwebpurchases      2240 non-null   int64
 17  numcatalogpurchases  2240 non-null   int64
 18  numstorepurchases    2240 non-null   int64
 19  numwebvisitsmonth    2240 non-null   int64
 20  acceptedcmp3         2240 non-null   int64
 21  acceptedcmp4         2240 non-null   int64
 22  acceptedcmp5         2240 non-null   int64
 23  acceptedcmp1         2240 non-null   int64
 24  acceptedcmp2         2240 non-null   int64
 25  complain             2240 non-null   int64
 26  z_costcontact        2240 non-null   int64
 27  z_revenue            2240 non-null   int64
 28  response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB